### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by mcollina** [mcollina/boot-in-the-arse#2]
I am wondering what is the best way to use `boot-in-the-arse`. Currently there are two options:

a. subclassing
b. passing another server through the constructor

Case a. works as expected, but it fills the object with the `boot-in-the-arse` properties. It would probably need to be more documented.

Case b. uses the passed object as the `context` and `this` in the plugin loading. However it does not expose `use`, the `'start'` event and the upcoming `ready()`  and `after()` #1.

I think there should be a _blessed_ way on using this.
What should we do?

I proposed we auto-bind `use`, `ready` and `after` in case b), so that they work as expected.

cc @mcdonnelldean @lucamaraschi

**Comment by lucamaraschi** [comment]
I personally do like the auto-binding method that you described in the case b as the subclassing in case a looks too mechanical and tedious for a good DX.

**Comment by mcdonnelldean** [comment]
B for me for sure.

**Comment by mcollina** [comment]
What happens if the target is not an EventEmitter? I don't think express apps are EE. Another way would be to provide a way to expose the status, e.g as 'app.booster'.

Errors could be emitter there, and users could rely on ready() to know if it was started, or use the start event on app.booster.
